CREATE TABLE IF NOT EXISTS thing (
  id          BIGINT        NOT NULL AUTO_INCREMENT PRIMARY KEY,

  name        VARCHAR(255)  NOT NULL,
  description VARCHAR(1024) NOT NULL,
  auth        VARCHAR(32)   NOT NULL DEFAULT '',
  https       TINYINT       NOT NULL DEFAULT 0,
  cors        VARCHAR(32)   NOT NULL DEFAULT 'unknown',
  link        VARCHAR(266)  NOT NULL DEFAULT  '',
  category    VARCHAR(255),

  created     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
  modified    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
